
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
       
        PTV_ADD_NEW : "PTV_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
        TRANSACTION_ADD_NEW : "TRANSACTION_ADD_NEW",
        PUBLICITE_ADD_NEW : "PUBLICITE_ADD_NEW",
        PROMO_ADD_NEW : "PROMO_ADD_NEW",
        MEMBRE_ADD_NEW : "MEMBRE_ADD_NEW",
        VENTE_FLASH_ADD_NEW : "VENTE_FLASH_ADD_NEW",
        PRODUIT_ADD_NEW :'PRODUIT_ADD_NEW',
        PDV_UPDATE : 'PDV_UPDATE',
        PRODUCT_UPDATE: 'PRODUCT_UPDATE',
        CATEGORIE_ADD:'CATEGORIE_ADD',

    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        TRANSACTION_DELETE : "TRANSACTION",
    },
});
